version: '2'
services:
  web:
    links:
      - database
      - redis
    build: .
    ports:
      - '3000:3000'
    env_file:
      - '.env'
    volumes_from:
      - container:chato-web-sync:rw
    volumes:
      - ./keys:/root/.ssh/
    command: [bundle, exec, puma]
    stop_signal: SIGINT
    stdin_open: true
    tty: true
  database:
    image: postgres
    volumes:
      - ./pgdata:/pgdata
    env_file:
      - '.env'
  redis:
    image: redis
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes_from:
      - container:chato-web-sync:rw
    volumes:
      - ./keys:/root/.ssh/
    ports:
      - "6379:6379"
    env_file:
      - '.env'
    links:
      - database
      - redis
volumes:
  chato-web-sync:
    external: true
